name: Continuous Integration

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests - Java version ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '14', '15', '16', '17', '18', '19' ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - run: make dependencies
      - run: make all
      - run: make test

  publish:
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    name: Publish handout
    runs-on: ubuntu-latest
    concurrency: publish-handout
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - run: make build/handout/

      - run: |
          cd build/handout/

          git init
          git branch -m main
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # https://stackoverflow.com/a/18999726
          git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.DEV8 }}@github.com/nus-cs5223/dslabs-template"
          git fetch
          git reset origin/main
          git commit -a -m "Auto-commit built handout"

          git push origin main

          rm -rf .git
          cd ../..
